#############################################################################
# Makefile for building: gestione_attivita
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  gestione_attivita.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile gestione_attivita.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I. -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = gestione_attivita1.0.0
DISTDIR = /home/student/workspace/.tmp/gestione_attivita1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/aarch64-linux-gnu
LIBS          = $(SUBLIBS) /usr/lib/aarch64-linux-gnu/libQt6Widgets.so /usr/lib/aarch64-linux-gnu/libQt6Gui.so /usr/lib/aarch64-linux-gnu/libGLX.so /usr/lib/aarch64-linux-gnu/libOpenGL.so /usr/lib/aarch64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		modello/attivita.cpp \
		modello/gestioneattivita.cpp \
		modello/lavoro.cpp \
		modello/personale.cpp \
		modello/sociale.cpp \
		modello/visitamedica.cpp \
		modello/attivitafactory.cpp \
		modello/jsonrepo.cpp \
		modello/attivita_table.cpp \
		gui/mainwindow.cpp \
		gui/attivitaform.cpp \
		gui/compilaformvisitor.cpp \
		gui/dettaglioattivitavisitor.cpp \
		gui/filemanager.cpp \
		gui/pannellodettagli.cpp \
		gui/menutoolbarmanager.cpp \
		gui/attivitacontroller.cpp moc_attivita_table.cpp \
		moc_mainwindow.cpp \
		moc_attivitaform.cpp \
		moc_pannellodettagli.cpp \
		moc_menutoolbarmanager.cpp \
		moc_attivitacontroller.cpp
OBJECTS       = main.o \
		attivita.o \
		gestioneattivita.o \
		lavoro.o \
		personale.o \
		sociale.o \
		visitamedica.o \
		attivitafactory.o \
		jsonrepo.o \
		attivita_table.o \
		mainwindow.o \
		attivitaform.o \
		compilaformvisitor.o \
		dettaglioattivitavisitor.o \
		filemanager.o \
		pannellodettagli.o \
		menutoolbarmanager.o \
		attivitacontroller.o \
		moc_attivita_table.o \
		moc_mainwindow.o \
		moc_attivitaform.o \
		moc_pannellodettagli.o \
		moc_menutoolbarmanager.o \
		moc_attivitacontroller.o
DIST          = /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/lex.prf \
		gestione_attivita.pro modello/attivita.h \
		modello/gestioneattivita.h \
		modello/lavoro.h \
		modello/personale.h \
		modello/sociale.h \
		modello/visitamedica.h \
		modello/attivitafactory.h \
		modello/interfaccia_repo.h \
		modello/jsonrepo.h \
		modello/attivitavisitor.h \
		modello/gestioneattivita_observer.h \
		modello/attivita_table.h \
		gui/mainwindow.h \
		gui/attivitaform.h \
		gui/compilaformvisitor.h \
		gui/dettaglioattivitavisitor.h \
		gui/filemanager.h \
		gui/pannellodettagli.h \
		gui/menutoolbarmanager.h \
		gui/attivitacontroller.h main.cpp \
		modello/attivita.cpp \
		modello/gestioneattivita.cpp \
		modello/lavoro.cpp \
		modello/personale.cpp \
		modello/sociale.cpp \
		modello/visitamedica.cpp \
		modello/attivitafactory.cpp \
		modello/jsonrepo.cpp \
		modello/attivita_table.cpp \
		gui/mainwindow.cpp \
		gui/attivitaform.cpp \
		gui/compilaformvisitor.cpp \
		gui/dettaglioattivitavisitor.cpp \
		gui/filemanager.cpp \
		gui/pannellodettagli.cpp \
		gui/menutoolbarmanager.cpp \
		gui/attivitacontroller.cpp
QMAKE_TARGET  = gestione_attivita
DESTDIR       = 
TARGET        = gestione_attivita


first: all
####### Build rules

gestione_attivita:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gestione_attivita.pro /usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/lex.prf \
		gestione_attivita.pro \
		/usr/lib/aarch64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/aarch64-linux-gnu/libQt6Gui.prl \
		/usr/lib/aarch64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile gestione_attivita.pro
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_chartsqml.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/lex.prf:
gestione_attivita.pro:
/usr/lib/aarch64-linux-gnu/libQt6Widgets.prl:
/usr/lib/aarch64-linux-gnu/libQt6Gui.prl:
/usr/lib/aarch64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile gestione_attivita.pro

qmake_all: FORCE


all: Makefile gestione_attivita

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents modello/attivita.h modello/gestioneattivita.h modello/lavoro.h modello/personale.h modello/sociale.h modello/visitamedica.h modello/attivitafactory.h modello/interfaccia_repo.h modello/jsonrepo.h modello/attivitavisitor.h modello/gestioneattivita_observer.h modello/attivita_table.h gui/mainwindow.h gui/attivitaform.h gui/compilaformvisitor.h gui/dettaglioattivitavisitor.h gui/filemanager.h gui/pannellodettagli.h gui/menutoolbarmanager.h gui/attivitacontroller.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp modello/attivita.cpp modello/gestioneattivita.cpp modello/lavoro.cpp modello/personale.cpp modello/sociale.cpp modello/visitamedica.cpp modello/attivitafactory.cpp modello/jsonrepo.cpp modello/attivita_table.cpp gui/mainwindow.cpp gui/attivitaform.cpp gui/compilaformvisitor.cpp gui/dettaglioattivitavisitor.cpp gui/filemanager.cpp gui/pannellodettagli.cpp gui/menutoolbarmanager.cpp gui/attivitacontroller.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/aarch64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_attivita_table.cpp moc_mainwindow.cpp moc_attivitaform.cpp moc_pannellodettagli.cpp moc_menutoolbarmanager.cpp moc_attivitacontroller.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_attivita_table.cpp moc_mainwindow.cpp moc_attivitaform.cpp moc_pannellodettagli.cpp moc_menutoolbarmanager.cpp moc_attivitacontroller.cpp
moc_attivita_table.cpp: modello/attivita_table.h \
		modello/gestioneattivita.h \
		modello/gestioneattivita_observer.h \
		modello/attivita.h \
		modello/attivitavisitor.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/student/workspace/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/student/workspace -I/home/student/workspace -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/aarch64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/aarch64-linux-gnu/13/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include modello/attivita_table.h -o moc_attivita_table.cpp

moc_mainwindow.cpp: gui/mainwindow.h \
		gui/attivitaform.h \
		modello/attivita.h \
		modello/attivitavisitor.h \
		gui/compilaformvisitor.h \
		gui/lavorouifactory.h \
		gui/attivitauifactory.h \
		modello/lavoro.h \
		gui/personaleuifactory.h \
		modello/personale.h \
		gui/socialeuifactory.h \
		modello/sociale.h \
		gui/visitamedicauifactory.h \
		modello/visitamedica.h \
		modello/gestioneattivita_observer.h \
		modello/attivita_table.h \
		modello/gestioneattivita.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/student/workspace/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/student/workspace -I/home/student/workspace -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/aarch64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/aarch64-linux-gnu/13/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include gui/mainwindow.h -o moc_mainwindow.cpp

moc_attivitaform.cpp: gui/attivitaform.h \
		modello/attivita.h \
		modello/attivitavisitor.h \
		gui/compilaformvisitor.h \
		gui/lavorouifactory.h \
		gui/attivitauifactory.h \
		modello/lavoro.h \
		gui/personaleuifactory.h \
		modello/personale.h \
		gui/socialeuifactory.h \
		modello/sociale.h \
		gui/visitamedicauifactory.h \
		modello/visitamedica.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/student/workspace/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/student/workspace -I/home/student/workspace -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/aarch64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/aarch64-linux-gnu/13/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include gui/attivitaform.h -o moc_attivitaform.cpp

moc_pannellodettagli.cpp: gui/pannellodettagli.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/student/workspace/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/student/workspace -I/home/student/workspace -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/aarch64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/aarch64-linux-gnu/13/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include gui/pannellodettagli.h -o moc_pannellodettagli.cpp

moc_menutoolbarmanager.cpp: gui/menutoolbarmanager.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/student/workspace/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/student/workspace -I/home/student/workspace -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/aarch64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/aarch64-linux-gnu/13/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include gui/menutoolbarmanager.h -o moc_menutoolbarmanager.cpp

moc_attivitacontroller.cpp: gui/attivitacontroller.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/student/workspace/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/student/workspace -I/home/student/workspace -I/usr/include/aarch64-linux-gnu/qt6 -I/usr/include/aarch64-linux-gnu/qt6/QtWidgets -I/usr/include/aarch64-linux-gnu/qt6/QtGui -I/usr/include/aarch64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/aarch64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/aarch64-linux-gnu/13/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include gui/attivitacontroller.h -o moc_attivitacontroller.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp gui/mainwindow.h \
		gui/attivitaform.h \
		modello/attivita.h \
		modello/attivitavisitor.h \
		gui/compilaformvisitor.h \
		gui/lavorouifactory.h \
		gui/attivitauifactory.h \
		modello/lavoro.h \
		gui/personaleuifactory.h \
		modello/personale.h \
		gui/socialeuifactory.h \
		modello/sociale.h \
		gui/visitamedicauifactory.h \
		modello/visitamedica.h \
		modello/gestioneattivita_observer.h \
		modello/attivita_table.h \
		modello/gestioneattivita.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

attivita.o: modello/attivita.cpp modello/attivita.h \
		modello/attivitavisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o attivita.o modello/attivita.cpp

gestioneattivita.o: modello/gestioneattivita.cpp modello/gestioneattivita.h \
		modello/attivita.h \
		modello/attivitavisitor.h \
		modello/interfaccia_repo.h \
		modello/gestioneattivita_observer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gestioneattivita.o modello/gestioneattivita.cpp

lavoro.o: modello/lavoro.cpp modello/lavoro.h \
		modello/attivita.h \
		modello/attivitavisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lavoro.o modello/lavoro.cpp

personale.o: modello/personale.cpp modello/personale.h \
		modello/attivita.h \
		modello/attivitavisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o personale.o modello/personale.cpp

sociale.o: modello/sociale.cpp modello/sociale.h \
		modello/attivita.h \
		modello/attivitavisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sociale.o modello/sociale.cpp

visitamedica.o: modello/visitamedica.cpp modello/visitamedica.h \
		modello/attivita.h \
		modello/attivitavisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o visitamedica.o modello/visitamedica.cpp

attivitafactory.o: modello/attivitafactory.cpp modello/attivitafactory.h \
		modello/lavoro.h \
		modello/attivita.h \
		modello/attivitavisitor.h \
		modello/personale.h \
		modello/sociale.h \
		modello/visitamedica.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o attivitafactory.o modello/attivitafactory.cpp

jsonrepo.o: modello/jsonrepo.cpp modello/jsonrepo.h \
		modello/interfaccia_repo.h \
		modello/attivitafactory.h \
		modello/lavoro.h \
		modello/attivita.h \
		modello/attivitavisitor.h \
		modello/personale.h \
		modello/sociale.h \
		modello/visitamedica.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jsonrepo.o modello/jsonrepo.cpp

attivita_table.o: modello/attivita_table.cpp modello/attivita_table.h \
		modello/gestioneattivita.h \
		modello/gestioneattivita_observer.h \
		modello/attivita.h \
		modello/attivitavisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o attivita_table.o modello/attivita_table.cpp

mainwindow.o: gui/mainwindow.cpp gui/attivitaform.h \
		modello/attivita.h \
		modello/attivitavisitor.h \
		gui/compilaformvisitor.h \
		gui/lavorouifactory.h \
		gui/attivitauifactory.h \
		modello/lavoro.h \
		gui/personaleuifactory.h \
		modello/personale.h \
		gui/socialeuifactory.h \
		modello/sociale.h \
		gui/visitamedicauifactory.h \
		modello/visitamedica.h \
		gui/mainwindow.h \
		modello/gestioneattivita_observer.h \
		modello/attivita_table.h \
		modello/gestioneattivita.h \
		gui/filemanager.h \
		gui/pannellodettagli.h \
		gui/menutoolbarmanager.h \
		gui/attivitacontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o gui/mainwindow.cpp

attivitaform.o: gui/attivitaform.cpp gui/attivitaform.h \
		modello/attivita.h \
		modello/attivitavisitor.h \
		gui/compilaformvisitor.h \
		gui/lavorouifactory.h \
		gui/attivitauifactory.h \
		modello/lavoro.h \
		gui/personaleuifactory.h \
		modello/personale.h \
		gui/socialeuifactory.h \
		modello/sociale.h \
		gui/visitamedicauifactory.h \
		modello/visitamedica.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o attivitaform.o gui/attivitaform.cpp

compilaformvisitor.o: gui/compilaformvisitor.cpp gui/compilaformvisitor.h \
		modello/attivitavisitor.h \
		modello/attivita.h \
		gui/attivitaform.h \
		gui/lavorouifactory.h \
		gui/attivitauifactory.h \
		modello/lavoro.h \
		gui/personaleuifactory.h \
		modello/personale.h \
		gui/socialeuifactory.h \
		modello/sociale.h \
		gui/visitamedicauifactory.h \
		modello/visitamedica.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o compilaformvisitor.o gui/compilaformvisitor.cpp

dettaglioattivitavisitor.o: gui/dettaglioattivitavisitor.cpp gui/dettaglioattivitavisitor.h \
		modello/attivitavisitor.h \
		modello/personale.h \
		modello/attivita.h \
		modello/sociale.h \
		modello/lavoro.h \
		modello/visitamedica.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dettaglioattivitavisitor.o gui/dettaglioattivitavisitor.cpp

filemanager.o: gui/filemanager.cpp gui/filemanager.h \
		modello/gestioneattivita.h \
		modello/jsonrepo.h \
		modello/interfaccia_repo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filemanager.o gui/filemanager.cpp

pannellodettagli.o: gui/pannellodettagli.cpp gui/pannellodettagli.h \
		gui/dettaglioattivitavisitor.h \
		modello/attivitavisitor.h \
		modello/attivita.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pannellodettagli.o gui/pannellodettagli.cpp

menutoolbarmanager.o: gui/menutoolbarmanager.cpp gui/menutoolbarmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o menutoolbarmanager.o gui/menutoolbarmanager.cpp

attivitacontroller.o: gui/attivitacontroller.cpp gui/attivitacontroller.h \
		modello/gestioneattivita.h \
		modello/attivita.h \
		modello/attivitavisitor.h \
		gui/pannellodettagli.h \
		gui/attivitaform.h \
		gui/compilaformvisitor.h \
		gui/lavorouifactory.h \
		gui/attivitauifactory.h \
		modello/lavoro.h \
		gui/personaleuifactory.h \
		modello/personale.h \
		gui/socialeuifactory.h \
		modello/sociale.h \
		gui/visitamedicauifactory.h \
		modello/visitamedica.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o attivitacontroller.o gui/attivitacontroller.cpp

moc_attivita_table.o: moc_attivita_table.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_attivita_table.o moc_attivita_table.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_attivitaform.o: moc_attivitaform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_attivitaform.o moc_attivitaform.cpp

moc_pannellodettagli.o: moc_pannellodettagli.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pannellodettagli.o moc_pannellodettagli.cpp

moc_menutoolbarmanager.o: moc_menutoolbarmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_menutoolbarmanager.o moc_menutoolbarmanager.cpp

moc_attivitacontroller.o: moc_attivitacontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_attivitacontroller.o moc_attivitacontroller.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

